prisma_cloud:
  aws_region: us-east-1
  aws_sqs_queue: prisma-special-queue
  aws_account_number : 106715121600
  # "https://queue.amazonaws.com/769125279023/prisma-special-queue"
  #syslog_host: 10.141.250.73
  syslog_host: 10.141.222.250

  syslog_port: 514
 
